# Generated by Django 3.2.9 on 2021-11-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currentshowerdata',
            fields=[
                ('idcurrentshowerdata', models.IntegerField(db_column='idcurrentShowerData', primary_key=True, serialize=False)),
                ('targettime', models.IntegerField(blank=True, db_column='targetTime', null=True)),
                ('showercount', models.IntegerField(blank=True, db_column='showerCount', null=True)),
            ],
            options={
                'db_table': 'currentShowerData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showerdataset',
            fields=[
                ('idshowerdataset', models.IntegerField(db_column='idshowerDataSet', primary_key=True, serialize=False)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=45, null=True)),
                ('averageemissions', models.IntegerField(blank=True, db_column='averageEmissions', null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showerDataSet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showerlog',
            fields=[
                ('idshower', models.IntegerField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('takentime', models.IntegerField(blank=True, db_column='takenTime', null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('emissions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showerLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pw', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
