# Generated by Django 3.2.9 on 2021-12-04 17:29

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('idfamily', models.IntegerField(db_column='idFamily', primary_key=True, serialize=False)),
                ('familycap', models.CharField(blank=True, db_column='familyCap', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personalshowerdata',
            fields=[
                ('idcurrentshowerdata', models.AutoField(db_column='idcurrentShowerData', primary_key=True, serialize=False)),
                ('targettime', models.IntegerField(blank=True, db_column='targetTime', null=True)),
                ('reduction', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Personalshowerdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showerdataset',
            fields=[
                ('idshowerdataset', models.IntegerField(db_column='idshowerDataSet', primary_key=True, serialize=False)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=45, null=True)),
                ('averageemissions', models.IntegerField(blank=True, db_column='averageEmissions', null=True)),
            ],
            options={
                'db_table': 'showerDataSet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Showerlog',
            fields=[
                ('idshower', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('takentime', models.IntegerField(blank=True, db_column='takenTime', null=True)),
                ('emissions', models.IntegerField(blank=True, null=True)),
                ('sum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'showerLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.authuser')),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
