# Generated by Django 3.2.9 on 2021-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalshowerdata',
            fields=[
                ('idcurrentshowerdata', models.IntegerField(db_column='idcurrentShowerData', primary_key=True, serialize=False)),
                ('targettime', models.IntegerField(blank=True, db_column='targetTime', null=True)),
                ('reduction', models.IntegerField(blank=True, db_column='reduction', null=True)),
            ],
            options={
                'db_table': 'PersonalShowerData',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Currentshowerdata',
        ),
    ]
