# Generated by Django 3.2.9 on 2021-11-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211126_1010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personalshowerdata',
            table='Personalshowerdata',
        ),
    ]
